### ISSUE TITLE
bedGraph requires tabs, even though UCSC example is spaces

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#12]
How about accepting both?

https://genome.ucsc.edu/goldenpath/help/bedgraph.html

And I did not understand what the error was because immediately after an error message is displayed, the program opens, so you never see it.

**Comment by dariober** [comment]
Hi- Thanks for taking time for testing and reporting issues! 
About supporting spaces in bedgraph, the UCSC page doesn't explicitly says that columns should be tab separated but I'm pretty sure they must be. At least, tools like bedtools, tabix, samtools etc break if columns were space separated. 

So no, I don't think spaces should be supported as tab separators. If you happen to have space separated bedgraphs than I would suggest converting them to tab (something like `tr ' ' '\t' < space.bedgraph > tab.bedgraph` will do.)

On the other hand, it's true, an invalid bedgraph is read without throwing an explicit error and it seems to produce an empty track. This needs to be fixed!

**Comment by endrebak** [comment]
I'm not just testing it, I've started to seriously use it :)

I have two chip-seq callers coming out (epic and triform2) where I will include an `--ASCIIgenome` option to create a script file that can generate images in ASCIIgenome.

**Comment by endrebak** [comment]
This is obsolete with #20

**Comment by dariober** [comment]
Space separator in bed/bedgraph is allowed in forthcoming version 1.18.0
