### ISSUE TITLE
Instead of telling me that the chromosome does not exist it just goes to an empty region.

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#13]
I tried `goto 1:123-456` but the magic words were `goto chr1:123-456`. Instead of showing a blank region, it should tell me there is no such chromosome.

Would be neat if it understood `1` to mean `chr1` and vice versa.

**Comment by dariober** [comment]
>Would be neat if it understood 1 to mean chr1 and vice versa.

Yes, that's true. I thought about it but didn't implement to keep things simpler at this stage. This UCSC vs ENSEMBL naming is such a pain!

About going to a blank region if a chromosome doesn't exist, I think it's the correct behaviour unless a genome dictionary is available (see [Genome option](https://github.com/dariober/ASCIIGenome#genome-option)). Without a genome dictionary you can't tell whether a chromosome doesn't exist or simply there are no features on that chromosome. For example, in a chipseq file with no peaks on chrM, ASCIIGenome cannot tell whether chrM doesn't exist or it is empty so it does what the user says, go there. If you supply a genome file then you get a warning if you try to access a non-existing chrom.
