### ISSUE TITLE
Store command history between sessions?

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#14]
Just an idea, dunno if it is hard to implement or not.

**Comment by dariober** [comment]
Yes, it shouldn't be difficult at all I think, I'll work on it.

**Comment by dariober** [comment]
In version 0.4.0 I put an (experimental) option to save sessions that can be reloaded.

```
sessionSave filename
      Experimental: Save the current settings to file suitable to be reloaded by
      ASCIIGenome. `sessionSave` writes to file a set of commands to reproduce the
      current settings: tracks, colors, heights etc. It's not meant to be a perfect
      replica, rather it's a shortcut to avoid re-typing commands. Example:
      ```
      sessionSave session.txt
      ```
      Quit session and reload with:
      ```
      ASCIIGenome -x session.txt
      ```
```

It's not quite saving command history but maybe close. By the way, in 0.4.0 there is a `cmdHistory` command, similar the Shell history program, to list the executed commands.

As before, I'm going to close this but feel free to send bugs/issues/comments

**Comment by andreirozanski** [comment]
Hi Dario, 

Thanks for the amazing tool. It is really helpful. 
I am using version 1.16.0. It seems it does not have the sessionSave feature. Is there any other option to "save" current settings? i.e mostly color assigned to different features, opened files and order of the tracks?
I am sorry if I have missed that at the documentation. 

Best,
AndreiR

**Comment by dariober** [comment]
Hi AndreiR - Thanks for your interest! I'm afraid I didn't get around implementing `sessionSave` in a decent way (but I keep it in mind!). Closest solution is still to use the `-x` argument with a string or file that, unfortunately, has to be prepared by the user.

**Comment by andreirozanski** [comment]
Hi Dario,
That's already pretty good for what I need! Thanks for pointing me to that and again thanks for the amazing software :)
