### ISSUE TITLE
GTF/GTT: Instead of displaying OOOOOO write snoRNA:snoRNA:snoRNA

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#15]
This way I could more easily share the output of ASCIIgenome to others without including a legend. 

Perhaps better if the separator is not `:`, but `+` for forward strand and `-` for reverse strand?

**Comment by dariober** [comment]
Mmm... I see, if the feature is big enough why not to use the full description instead of the single letter codes? Again, at this early stage I favoured a simpler implementation.

I'll close the issue now but I'll keep it mind, thanks!
