### ISSUE TITLE
Are tabix-indexed GFFs/GTFs accepted?

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#16]
GFFs takes a while to load, which is a bother since I want to visualize hundreds of regions. Therefore I am wondering whether tabix-indexed GFFs/GTFs are accepted? (Haven't been able to index any yet, seems like a hassle.)

An alternative way to solve this would be to have ASCIIGenome accept a bed file of regions to create images from, so that I would only need to load the input files once.

**Comment by dariober** [comment]
> tabix-indexed GFFs/GTFs are accepted

Yes, tabix indexing is supported (there is a note in [Supported input](https://github.com/dariober/ASCIIGenome#supported-input) ). If your gff file is already sorted by position you would do:

```
bgzip genes.gff
tabix -p gff genes.gff.gz
```

If it's not sorted by position you can use unix sort or bedtools sort, but take care of not sorting any of the optional header lines or the optional fasta sequences appended to it!

>An alternative way to solve this would be to have ASCIIGenome accept a bed file of regions to create images from, so that I would only need to load the input files once.

Yes that might be an idea...

**Comment by endrebak** [comment]
What I want to do seems to be possible like this:

asciigenome -x 'goto chr10:69223041-69223072 && save .png && chr3:196318127-196318155 && save .png'

A mildly annoying thing is that it reads all the files and then tells me if there is a mistake in the commands.
