### ISSUE TITLE
Cntrl-z and then fg gives blank screen

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#17]
Dunno if this is hard to fix. You only have to press enter to have the screen reappear though.

Also, pressing `cntrl-z/cntrl-c/cntrl-d` without meaning it is all too easy for me. Perhaps adding a prompt (`Do you really want to exit`) would be good?

**Comment by dariober** [comment]
Yeah I see, I'm not sure if I can capture `CTRL-C` before the OS does and kills the program... On the other hand, it's like the `rm` command, by default it does what you tell it to do, no warning, no going back!
