### ISSUE TITLE
When using `-x <multiple gotos and saves>` only saves last region.

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#18]
This is my command:

```
ASCIIGenome -nf -ni PolII.bed PolII_tabs.bedgraph -fa ~/genomes/hg38.fa \
 -x 'goto chr10:69223041-69223072 && save .png && goto chr3:196318127-196318155 && save .png && goto chr8:1755859-1755886 && save .png'
```

This is the output:

```
endrebak@havpryd ~/c/asciigenome> ls -latrh *png
-rw-r--r-- 1 endrebak endrebak 53K Aug  3 10:17 chr8_1755859-1755886.png
```

Note that 

```
ASCIIGenome -nf -ni PolII.bed PolII_tabs.bedgraph -fa ~/genomes/hg38.fa \
 -x 'goto chr10:69223041-69223072 && save .png' \
 -x 'goto chr3:196318127-196318155 && save .png'
```

did not work either.

Note that if you fix this you fix #16 (creating many pngs in one go).

Sorry for the issue storm. I'll calm down now, but this seems pretty essential :)

For now I will use a loop and an indexed gtf file.

**Comment by dariober** [comment]
Indeed, the chain of commands is evaluated at the end, which is not really intentional as chaining was an afterthought. I think passing a file of regions for batch processing is the way to go.

>Sorry for the issue storm. 

No worries! Keep them coming.

**Comment by endrebak** [comment]
If you decide to have a file for regions with batch processing it would be neat if each region could have some additional metadata printed above them.

Here is a bed file I use to include some info about each region I want pictured:

```
chr1	16514270	16514470	'chr1 16514270 16514470 1 1.67636505625e 105'	0	.
chr11	65498880	65499153	'chr11 65498880 65499153 1 8.04671131089e 74'	0	.
chr1	44721845	44722111	'chr1 44721845 44722111 1 8.34820427584e 67'	0	.
chr1	11907928	11908223	'chr1 11907928 11908223 1 2.36881034767e 63'	0	.
```

As you can see, the name field in each bed contains the location, peak type and fdr score. I'd like this info to be centered above each image. In the picture below the info is rather inconspicuous.

![chr1_16514271-16514426](https://cloud.githubusercontent.com/assets/17778898/17360110/220626d8-596a-11e6-96ff-0b58d59572e9.png)

If you take a file of regions to graph, you know the start and end and can center the info (field 4) above on the display. As you can see, the info I try to add is almost invisible.

Perhaps the user should be allowed to have several info lines per image? Then I could add more info, like the next/previous gene and the distance to them.

**Comment by endrebak** [comment]
Also allowing an optional line or two of whitespace between each track would be good for easing the mental work needed to parse the graphs.

And I'd like to remove a few of the lines (first, third and bottom perhaps).

**Comment by dariober** [comment]
>Perhaps the user should be allowed to have several info lines per image

Mmmh I see but this might become a bit tricky to handle, also for the user. By the way, maybe you haven't noticed the `print/printFull` commands, if you enable them for the tracks of your choice you can print the entire feature lines, without having to stuff everything in the 4th column. But of course, the font size will be small the same...

>Also allowing an optional line or two of whitespace between each track

I guess this is not to hard to implement.

Also, I realized that enabling colours in the png output might not be too difficult, that would make the visual output a bit nicer.

**Comment by endrebak** [comment]
Yes! Colors would be awesome.

And please say no liberally. It is better that you keep your software lean so that it is easy to modify and read. Making a nice report is probably better to do with a wrapper script when I think about it.

**Comment by endrebak** [comment]
> I think passing a file of regions for batch processing is the way to go.

If you choose to implement this, it would be helpful to be able to choose whether to get text or png when batching.

**Comment by endrebak** [comment]
Do not mean to nag, but I still *really* want this. Proof: added ASCIIGenome output to my poster: https://github.com/endrebak/git-lfs/blob/master/ChIPSeq.pdf

I have two ChIP-Seq callers where I intend to use ASCIIGenome to visualize all the regions afterwards. For PolII or H3K27me3 this means starting ASCIIGenome 10000 > times. Starting the jvm 10k times is expensive, would be like three hours for 10 k regions if starting the jvm takes one second. Therefore I think a batch-mode is necessary: the three hours would probably shrink to less than a minute if you just used one session. 

If you do not intend to add this feature I can easily incorporate ASCIIGenome in a jar of my own like ASCIIGenome-batch. Do not know java though so I would have to write it in Clojure or Frege.

**Comment by dariober** [comment]
Hi- Thanks for sharing the poster, looks interesting! About the batch mode, I keep it in mind but I can't tell when I'm going to implement it. It shouldn't be too difficult but it needs some re-working. What input files are you planning to use for visualization? If you use bam it's probably going to be quite slow anyway. Bigwig should be much faster but still printing >10k regions will take some time.

**Comment by endrebak** [comment]
Thanks. If I get more time (I will sometime in the future), I'll look into
java and try to do it myself :)

**Comment by dariober** [comment]
Hello- If still interested in ASCIIGenome, I have just uploaded version 0.4.0 which addresses most of the points here. In particular, batch processing can now be accomplished with the `-b/--batch` option. See [batch processing](https://github.com/dariober/ASCIIGenome#batch-processing) in README file. 
Color in png output is enabled.  

See also [changelog](https://github.com/dariober/ASCIIGenome/blob/master/CHANGELOG.md) for an (incomplete) list of changes.

I'm going to close this issue just now but feel free to reopen and/or send new issues!
