### ISSUE TITLE
Adding ASCIIGenome to bioconda

### ISSUE THREAD

**Issue by endrebak** [dariober/ASCIIGenome#22]
I'm on it: https://github.com/bioconda/bioconda-recipes/issues/2125

but will need further help/more time. Just in case sb was thinking of trying the same.

**Comment by dariober** [comment]
Thanks for keeping me posted!

**Comment by endrebak** [comment]
The unstoppable daler helped me fix the install script. 

`ASCIIgenome` is now a part of bioconda (I changed the default RAM settings to ~8GB).

I love your script and am including ASCII peak reports in triform2 so it was done for selfish reasons, but hope it will be useful. I find linuxbrew hard to install, perhaps sb else will prefer the bionconda version.

If you ping me here on updates I'll update the bioconda edition.

**Comment by dariober** [comment]
Ok, cool! A couple of things... Java is quite greedy abut memory if you allow it 8GB it might take all of it, even if it could get away with much less (Java experts would cringe for putting this down in such a crude way...). Setting 8GB by default could result in problems with memory allocation with those users that don't have that much and even if their data is smaller.

Other thing... In the branch version `color_etc`, v0.3.0, I'm making some changes where the most notable are : png output is now with colours. Pulling data from UCSC can be done with the syntax `genome:table` (e.g. `hg19:refGene`) although it has some glitches which I'm going to clarify in the README.

**Comment by endrebak** [comment]
Hi -- slightly unrelated question: were you able to get the list of all possible tracks (like refGene) for a genome in some way? I am thinking of creating such a list by parsing the source of UCSC webpages: https://genome.ucsc.edu/cgi-bin/hgTracks?org=human&db=hg19&singleSearch=knownCanonical&position=GABRA3

The source looks like this, so it is easily parseable:

```HTML
<td align=left><a title='encode project' href='../ENCODE'><img height='16' width='16' src='../images/encodeThumbnail.jpg'></a>
<A HREF="../cgi-bin/hgTrackUi?hgsid=511380963_M1kYMmznQwRaaZUlOq5tj40NT5S2&c=chrX&g=wgEncodeRbpSuper" title="ENCODE RNA Binding Proteins"> ENC RNA Binding...<BR> </A><SELECT NAME='wgEncodeRbpSuper' class='hiddenText visDD' style='width: 70px'>
<OPTION SELECTED>hide</OPTION>
<OPTION>show</OPTION>
</SELECT>
</td><td align=left><a title='encode project' href='../ENCODE'><img height='16' width='16' src='../images/encodeThumbnail.jpg'></a>
<A HREF="../cgi-bin/hgTrackUi?hgsid=511380963_M1kYMmznQwRaaZUlOq5tj40NT5S2&c=chrX&g=wgEncodeTfBindingSuper" title="ENCODE Transcription Factor Binding"> ENC TF Binding...<BR> </A><SELECT NAME='wgEncodeTfBindingSuper' class='hiddenText visDD' style='width: 70px'>
<OPTION SELECTED>hide</OPTION>
<OPTION>show</OPTION>
</SELECT>
</td>
```

I'm just wondering since you wrote: 

> Pulling data from UCSC can be done with the syntax genome:table (e.g. hg19:refGene) although it has some glitches which I'm going to clarify in the README.

This makes it sound like you were able to get a list of track names in some way.

**Comment by dariober** [comment]
Hi- 

>This makes it sound like you were able to get a list of track names in some way.

No, I'm not aiming at getting track names. Instead, I assume the user knows already how the database is called (e.g. hg19) and how the track is named (e.g. refGene), so I don't need to get the list of track names. 

About your question, I don't have a good answer really, maybe one option is to query the UCSC Genome Browser database with (for hg19):

```
mysql --user=genome --host=genome-mysql.cse.ucsc.edu -A -e "SHOW TABLES FROM hg19"
```

Assuming (big if) that "table" and "track" are the same thing.

Other options could make use of some bioconductor package (surely there is one).

Dario

**Comment by endrebak** [comment]
Thanks. Good to know, that means I am not duplicating your work :)
