### ISSUE TITLE
brew installation

### ISSUE THREAD

**Issue by dalloliogm** [dariober/ASCIIGenome#3]
It would be good to have a brew formula, to install Asciigenome more easily.

(I've already written it, I'll send a push request to linuxbrew in a few minutes)

**Comment by dalloliogm** [comment]
Here it is. I've created a pull request, but it may be rejected if the repository is not notable enough (<20 forks, <20 watchers and <50 stars). Still, the formula can be used to install it from brew.

Pull request: https://github.com/Homebrew/homebrew-science/pull/3830/files

What I don't like about the formula is that I have to sed your ASCIIGenome file to point to the location of the Jar file. Otherwise it gives the error:

> $ ASCIIGenome
> Error: Unable to access jarfile ../Cellar/asciigenome/0.1.0/bin/ASCIIGenome.jar

This is because brew installs the jar file within the Cellar folder, and then creates a symlink to it from the bin folder.

Could you please have a look at the formula, and see if you can improve it?  https://github.com/dalloliogm/homebrew-science/blob/asciigenome/asciigenome.rb

Thanks :-)

**Comment by dariober** [comment]
Thank you! I'll have a look although I'm not familiar with brew.

**Comment by dalloliogm** [comment]
Thanks!
In the end the formula was rejected because the software is yet not notable enough.
However this may change in the future :-)

Can you check if I missed any dependencies, and if you can think of a better installation test than ASCIIGenome --version, possibly downloading some data?

**Comment by dariober** [comment]
brew installation seems to work fine, so I'm going to close this issue. Thank you!
(But yes, better testing would be nice)
