### ISSUE TITLE
no http proxy support 

### ISSUE THREAD

**Issue by dalloliogm** [dariober/ASCIIGenome#6]
It seems that download from behind a proxy doesn't work.

For example, running the following command doesn't return any output:

`ASCIIGenome -g hg19     $encode/wgEncodeSydhTfbsGm10847NfkbTnfaIggrabPk.narrowPeak.gz     \ $encode/wgEncodeSydhTfbsGm10847NfkbTnfaIggrabSig.bigWig     \ $encode/wgEncodeSydhTfbsGm12892Pol2IggmusPk.narrowPeak.gz     \ $encode/wgEncodeSydhTfbsGm12892Pol2IggmusSig.bigWig
`

The command seems to be stuck, and no message is shown. I assume it is trying to download the files, but no verbose output is shown. Since it is taking a lot of time, I am also guessing that it is getting no connection.

**Comment by dariober** [comment]
Mmmh...

This is what I get from here (work) and when at home:

```
ASCIIGenome -g hg19 \
>     $encode/wgEncodeSydhTfbsGm10847NfkbTnfaIggrabPk.narrowPeak.gz \
>     $encode/wgEncodeSydhTfbsGm10847NfkbTnfaIggrabSig.bigWig \
>     $encode/wgEncodeSydhTfbsGm12892Pol2IggmusPk.narrowPeak.gz \
>     $encode/wgEncodeSydhTfbsGm12892Pol2IggmusSig.bigWig
Initializing coordinates... Reading file 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeSydhTfbs/wgEncodeSydhTfbsGm10847NfkbTnfaIggrabPk.narrowPeak.gz'... Done
INFO [2016-07-15 14:19:17,468]  [HttpUtils.java:827] [main]  Range-byte request succeeded
Reading file 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeSydhTfbs/wgEncodeSydhTfbsGm12892Pol2IggmusPk.narrowPeak.gz'... Done
```

It should take a couple of minutes, less for narrowPeak files only.

No, it doesn't download the files it connects directly through the remote files. If you use IGV, could you try to open these files with it? Through File -> Load from URL. 

ASCIIGenome uses some classes from IGV for connecting to remote files.

**Comment by dalloliogm** [comment]
In the end I discovered that this can be fixed by using the -Djava.net.useSystemProxies=true  option when calling java. This detects if the http_proxy variable is set, and uses it for the connection.

The example work correctly now, returning the "Range-byte request succeeded" message. It is a bit slow, but it may be because of the proxy here.

**Comment by dariober** [comment]
Thanks a lot for fixing this! I edited the README file to add this fix.
